
require('./lib/registerDapp')
require('./lib/sendMoney')
require('./lib/changeAschConfig')
require('./lib/startUpCheck')
require('./lib/deploy')
require('./lib/createLogDir')
require('./lib/service')
require('./lib/serializedNewDappId')
require('./lib/checkPort')
require('./lib/watcher')
require('./lib/checkPublicDistDir')
